#!/bin/bash

echo "🤖 Testing AI Service..."
echo "=========================="

# Run AI service tests
npm test -- --testPathPattern=aiService.test.ts --verbose

echo ""
echo "✅ AI Service Tests Complete!"
echo ""
echo "🧪 Test Coverage:"
echo "• Event Creation Recognition"
echo "• System Status Queries" 
echo "• Cost Analysis Queries"
echo "• User Activity Queries"
echo "• Security Queries"
echo "• Help and General Queries"
echo "• Event Data Extraction"
echo "• Error Handling"
echo "• Confirmation Flow"
echo ""
echo "🎯 Key Test Scenarios:"
echo "• 'make an event for double lake recreation area'"
echo "• 'create event for september 15-18'"
echo "• 'system status'"
echo "• 'cost analysis'"
echo "• 'help'"
echo ""
echo "📊 Expected Results:"
echo "• All event creation patterns should be recognized"
echo "• Event data should be extracted correctly"
echo "• System queries should return appropriate responses"
echo "• Error handling should work gracefully"
echo ""
echo "🔧 To run specific tests:"
echo "npm test -- --testNamePattern='Event Creation Recognition'"
echo "npm test -- --testNamePattern='System Status Queries'"
echo ""
echo "🚀 To test the AI manually:"
echo "1. Go to Admin AI page"
echo "2. Try: 'make an event for double lake recreation area'"
echo "3. Try: 'show system status'"
echo "4. Try: 'help'"
