name: Test Deployment Setup

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false --testTimeout=120000
    
    - name: Build project
      run: npm run build
      env:
        CI: false
    
    - name: Check Firebase configuration
      run: |
        echo "Firebase project: pack-1703-portal"
        echo "Build directory exists: $(ls -la build/)"
        echo "✅ Setup test completed successfully!"
